-- autogenerated lush spec on Sat Apr 12 21:52:16 2025
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv

-- Define our color palette
local colors = {
	-- Grayscale palette (slate-like colors)
	slate50 = "#f8fafc",
	slate100 = "#f1f5f9",
	slate200 = "#e2e8f0",
	slate300 = "#cbd5e1",
	slate400 = "#94a3b8",
	slate500 = "#64748b",
	slate600 = "#475569",
	slate700 = "#334155",
	slate800 = "#1e293b",
	slate900 = "#0f172a",
	slate950 = "#020617",

	-- Accent colors
	rose = hsluv("#f7768e"),
	leaf = hsluv("#73daca").da(8).de(5),
	wood = hsluv("#e0af68"),
	water = hsluv("#7aa2f7"),
	blossom = hsluv("#bb9af7"),
	sky = hsluv("#2ac3de"),
	orange = hsluv("#ff9e64").li(10),
	mint = hsluv("#73daca"), -- Additional name for leaf

	-- Additional colors
	yellow = "#facc15",
	teal = "#5DE4C7",

	-- Background colors
	bg0 = "#171922", -- darkest background
	bg1 = "#1B1E28", -- popup background
	bg2 = "#303340", -- highlights background

	white = "#FFFFFF",
}

local selection_style = { fg = hsluv("#a78bfa").de(10).li(5) }
-- local selection_style = { fg = hsluv("#f0abfc").de(10) }
-- local selection_style = { bg = hsluv("#4c1d95") }
-- local selection_style = { gui = "underline" }

local theme = lush(function(injected_functions)
	local sym = injected_functions.sym
	---@diagnostic disable: undefined-global
	-- selene: allow(undefined_variable)
	return {
		-- Base UI elements
		Normal({ fg = colors.slate300, bg = colors.bg0 }),
		NormalFloat({ fg = colors.slate300, bg = colors.bg1 }),
		NormalNC({ fg = colors.slate400, bg = colors.bg0 }),
		EndOfBuffer({ fg = colors.bg0 }),
		NonText({ fg = colors.slate700 }),
		Whitespace({ fg = colors.slate700 }),

		-- Line elements
		LineNr({ fg = colors.slate700 }),
		LineNrAbove({ fg = colors.slate700 }),
		LineNrBelow({ fg = colors.slate700 }),
		CursorLineNr({ fg = colors.leaf, gui = "bold" }),
		CursorLine({ bg = colors.bg1 }),
		CursorColumn({ bg = colors.bg1 }),
		SignColumn({ fg = colors.slate700, bg = colors.bg0 }),
		ColorColumn({ bg = colors.bg1 }),

		-- Status elements
		StatusLine({ fg = colors.slate300, bg = colors.bg1 }),
		StatusLineNC({ fg = colors.slate600, bg = colors.bg1 }),
		VertSplit({ fg = colors.bg1 }),
		WinSeparator({ fg = colors.bg1 }),

		-- Tabs and menus
		TabLine({ fg = colors.slate600, bg = colors.bg1 }),
		TabLineSel({ fg = colors.bg0, bg = colors.sky }),
		TabLineFill({ bg = colors.bg0 }),

		Pmenu({ fg = colors.slate300, bg = colors.bg1 }),
		PmenuSel({ bg = colors.bg2, fg = colors.white }),
		PmenuSbar({ bg = colors.bg1 }),
		PmenuThumb({ bg = colors.slate600 }),

		-- Search and visual
		Search({ fg = colors.bg0, bg = colors.water }),
		IncSearch({ fg = colors.bg0, bg = colors.yellow }),
		CurSearch({ fg = colors.bg0, bg = colors.yellow }),
		Visual({ bg = colors.slate600 }),
		VisualNOS({ bg = colors.slate600 }),

		-- Folds and diffs
		Folded({ fg = colors.water, bg = colors.bg2 }),
		FoldColumn({ fg = colors.slate600, bg = colors.bg0 }),

		DiffAdd({ bg = colors.leaf.darken(80) }),
		DiffChange({ bg = colors.water.darken(80) }),
		DiffDelete({ bg = colors.rose.darken(80) }),
		DiffText({ bg = colors.water.darken(60) }),

		-- Floating windows and borders
		FloatBorder({ fg = colors.slate600, bg = colors.bg1 }),
		FloatTitle({ fg = colors.sky, bg = colors.bg1 }),

		-- Messages
		ErrorMsg({ fg = colors.rose }),
		WarningMsg({ fg = colors.wood }),
		ModeMsg({ fg = colors.slate300, gui = "bold" }),
		MoreMsg({ fg = colors.water }),
		Question({ fg = colors.water }),

		-- Spell checking
		SpellBad({ sp = colors.rose, gui = "undercurl" }),
		SpellCap({ sp = colors.wood, gui = "undercurl" }),
		SpellRare({ sp = colors.leaf, gui = "undercurl" }),
		SpellLocal({ sp = colors.sky, gui = "undercurl" }),

		-- Cursor and highlighting
		Cursor({ fg = colors.bg0, bg = colors.slate300 }),
		lCursor({ fg = colors.bg0, bg = colors.slate300 }),
		CursorIM({ fg = colors.bg0, bg = colors.slate300 }),
		TermCursor({ gui = "reverse" }),
		MatchParen({ fg = colors.yellow, bg = "NONE", gui = "bold" }),

		-- Word highlighting (for plugins like vim-illuminate, CursorWord, etc.)
		IlluminatedWordText(selection_style),
		IlluminatedWordRead(selection_style),
		IlluminatedWordWrite(selection_style),

		-- For plugins that use different highlight groups
		CursorWord(selection_style),
		CursorWord0(selection_style),
		CursorWord1(selection_style),
		LspReferenceText(selection_style),
		LspReferenceRead(selection_style),
		LspReferenceWrite(selection_style),

		-- Syntax highlighting (core elements)
		-- Lowest priority/importance: comments
		Comment({ fg = colors.slate600, gui = "italic" }),

		-- Medium-low priority: language constructs
		Keyword({ fg = colors.slate500, gui = "italic" }), -- function, return, if, for...
		Statement({ fg = colors.slate500 }), -- any statement
		Conditional({ fg = colors.slate500 }), -- if, then, else, etc.
		Repeat({ fg = colors.slate500 }), -- for, do, while, etc.
		Label({ fg = colors.slate500 }), -- case, default, etc.
		Exception({ fg = colors.slate500 }), -- try, catch, throw
		Operator({ fg = colors.gray500 }), -- +, -, *, /, etc.

		-- Medium priority: preprocessing
		PreProc({ fg = colors.slate400 }), -- Generic preprocessor
		Include({ fg = colors.slate400 }), -- #include, import, etc.
		Define({ fg = colors.slate400 }), -- #define
		Macro({ fg = colors.slate400 }), -- Same as Define
		PreCondit({ fg = colors.slate400 }), -- #if, #else, etc.

		-- Medium-high priority: types and structure
		Type({ fg = colors.slate400 }), -- int, long, char, etc.
		StorageClass({ fg = colors.slate400 }), -- static, register, etc.
		Structure({ fg = colors.slate400 }), -- struct, union, enum, etc.
		Typedef({ fg = colors.slate400 }), -- A typedef

		-- Highest priority: identifiers and constants
		Identifier({ fg = colors.slate100 }), -- Variable names
		Constant({ fg = colors.slate300 }), -- Any constant
		String({ fg = colors.leaf }), -- String constant
		Character({ fg = colors.leaf }), -- Character constant
		Number({ fg = colors.slate300 }), -- Numeric constant
		Boolean({ fg = colors.slate300 }), -- Boolean constant
		Float({ fg = colors.slate300 }), -- Floating point constant

		-- Special cases
		Function({ fg = colors.slate300 }), -- Function names
		Special({ fg = colors.slate400 }), -- Special symbols
		SpecialChar({ fg = colors.slate400 }), -- Special character in a constant
		Tag({ fg = colors.slate400 }), -- HTML/XML tags
		Delimiter({ fg = colors.slate500 }), -- Delimiters {}[]()
		SpecialComment({ fg = colors.slate600, gui = "italic" }), -- Special comments
		Debug({ fg = colors.rose }), -- Debugging statements

		Underlined({ gui = "underline" }),
		Title({ fg = colors.water, gui = "bold" }),
		Error({ fg = colors.rose }),
		Todo({ fg = colors.wood, gui = "bold,italic" }),

		-- Tree-sitter
		sym("@text")({ fg = colors.slate300 }),
		sym("@text.emphasis")({ fg = colors.slate300, gui = "italic" }),
		sym("@text.strong")({ fg = colors.slate300, gui = "bold" }),
		sym("@text.underline")({ gui = "underline" }),
		sym("@text.title")({ Title }),
		sym("@text.uri")({ gui = "underline" }),

		sym("@comment")({ Comment }),
		sym("@punctuation")({ fg = colors.slate500 }),
		-- sym("@punctuation.bracket.svelte")({ fg = colors.orange }),

		sym("@constant")({ Constant }),
		sym("@constant.builtin")({ Constant }),
		sym("@string")({ String }),
		sym("@string.escape")({ SpecialChar }),
		sym("@string.special")({ SpecialChar }),
		sym("@character")({ Character }),
		sym("@number")({ Number }),
		sym("@boolean")({ Boolean }),
		sym("@float")({ Float }),

		sym("@function")({ Function }),
		sym("@function.builtin")({ Function }),
		sym("@function.call")({ Function }),
		sym("@function.macro")({ Macro }),

		sym("@method")({ Function }),
		sym("@method.call")({ Function }),

		sym("@constructor")({ fg = colors.slate400 }),
		sym("@parameter")({ fg = colors.slate100 }),

		sym("@keyword")({ Keyword }),
		sym("@keyword.function")({ Keyword }),
		sym("@keyword.operator")({ Operator }),
		sym("@operator")({ Operator }),
		sym("@operator.svelte")({ fg = colors.slate500 }),
		sym("@keyword.coroutine.svelte")({ fg = colors.orange }),
		sym("@keyword.conditional.svelte")({ fg = colors.orange }),
		sym("@keyword.svelte")({ fg = colors.orange }),

		sym("@conditional")({ Conditional }),
		sym("@repeat")({ Repeat }),
		sym("@exception")({ Exception }),

		sym("@variable")({ fg = colors.slate100 }),
		sym("@variable.builtin")({ fg = colors.slate300 }),

		sym("@type")({ Type }),
		sym("@type.builtin")({ Type }),
		sym("@type.definition")({ Typedef }),
		sym("@type.qualifier")({ fg = colors.slate500 }),

		sym("@structure")({ Structure }),
		sym("@field")({ fg = colors.slate100 }),
		sym("@property")({ fg = colors.slate100 }),

		sym("@include")({ Include }),
		sym("@define")({ Define }),
		sym("@preproc")({ PreProc }),
		sym("@debug")({ Debug }),
		sym("@tag")({ Tag }),
		sym("@tag.svelte")({ fg = colors.slate500, gui = "italic" }),

		-- LSP Semantic tokens
		sym("@lsp.type.namespace")({ Structure }),
		sym("@lsp.type.type")({ Type }),
		sym("@lsp.type.class")({ Structure }),
		sym("@lsp.type.enum")({ Structure }),
		sym("@lsp.type.interface")({ Structure }),
		sym("@lsp.type.struct")({ Structure }),
		sym("@lsp.type.parameter")({ fg = colors.slate100 }),
		sym("@lsp.type.variable")({ fg = colors.slate100 }),
		sym("@lsp.type.property")({ fg = colors.slate100 }),
		sym("@lsp.type.enumMember")({ Constant }),
		sym("@lsp.type.function")({ Function }),
		sym("@lsp.type.method")({ sym("@method") }),
		sym("@lsp.type.macro")({ Macro }),
		sym("@lsp.type.keyword")({ Keyword }),
		sym("@lsp.type.comment")({ Comment }),
		sym("@lsp.type.string")({ String }),
		sym("@lsp.type.number")({ Number }),
		sym("@lsp.type.regexp")({ SpecialChar }),
		sym("@lsp.type.operator")({ Operator }),
		sym("@lsp.type.decorator")({ sym("@function") }),

		-- Diagnostics
		DiagnosticError({ fg = colors.rose }),
		DiagnosticWarn({ fg = colors.wood }),
		DiagnosticInfo({ fg = colors.water }),
		DiagnosticHint({ fg = colors.leaf }),

		DiagnosticUnderlineError({ sp = colors.rose, gui = "undercurl" }),
		DiagnosticUnderlineWarn({ sp = colors.wood, gui = "undercurl" }),
		DiagnosticUnderlineInfo({ sp = colors.water, gui = "undercurl" }),
		DiagnosticUnderlineHint({ sp = colors.leaf, gui = "undercurl" }),

		-- Gitsigns
		GitSignsAdd({ fg = colors.leaf }),
		GitSignsChange({ fg = colors.water }),
		GitSignsDelete({ fg = colors.rose }),

		-- Common plugins
		-- nvim-cmp
		CmpItemAbbr({ fg = colors.slate300 }),
		CmpItemAbbrMatch({ fg = colors.sky }),
		CmpItemAbbrMatchFuzzy({ fg = colors.sky }),
		CmpItemKind({ fg = colors.water }),
		CmpItemMenu({ fg = colors.slate600 }),

		-- nvim-telescope
		TelescopePromptBorder({ FloatBorder }),
		TelescopeResultsBorder({ FloatBorder }),
		TelescopePreviewBorder({ FloatBorder }),
		TelescopePromptPrefix({ fg = colors.leaf }),
		TelescopeSelectionCaret({ fg = colors.leaf }),
		TelescopeSelection({ fg = colors.white, bg = colors.bg2 }),
		TelescopeMatching({ fg = colors.sky }),
	}
	-- selene: deny(undefined_variable)
	---@diagnostic enable: undefined-global
end)

return theme
